kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-event-logger-role-binding
subjects:
- kind: ServiceAccount
  name: k8s-event-logger-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-event-logger-role
  apiGroup: rbac.authorization.k8s.io
